### ISSUE TITLE
Can't Install Modpack

### ISSUE THREAD

**Issue by ShakesNH** [Cazadorsniper/PO3#101]
**Pack Version:**
3.0.38
**Description:**
When I installed the pack and attempted to run it, I was given this message.

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Steps to reproduce:**
Have Java Version 8 64 bit.
Open Twitch
Download PO3
Run PO3
Click Play in minecraft
get wrecked by not being able to play.

**Crash log:**
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Cazadorsniper** [comment]
need the whole crash in pastebin please.
