### ISSUE TITLE
BetterQuesting crashing player and unable to rejoin & BetterQuesting not syncing with party

### ISSUE THREAD

**Issue by JLBP** [Cazadorsniper/PO3#106]
**Pack Version:**
PO3-3.0.38 - Client
PO3-v.3.0.38_Server - Server
**Description:**
Having a issue with a player on my server  unable to sync his quests with his friend and then crashing out when trying to remove his friend.

I believe this is due to betterquesting. They have recently updated which apparently fixes the issue. I am unable to test this at the moment in time though.
**Steps to reproduce:**
- Player 1 adds a Player 2 to BetterQuesting Party
- BetterQuesting does not sync up with friend. So unable to share completed quests
- When Player 1 goes to remove Player 2. Player 1 crashes and is unable to rejoin

**Server console log:**
```[01:35:41] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent@3048b75c:
java.lang.NullPointerException: null
at bq_standard.tasks.TaskRetrieval.getPartyProgress(TaskRetrieval.java:461) ~[TaskRetrieval.class:?]
at bq_standard.tasks.TaskRetrieval.detect(TaskRetrieval.java:177) ~[TaskRetrieval.class:?]
at bq_standard.tasks.TaskRetrieval.tickTask(TaskRetrieval.java:85) ~[TaskRetrieval.class:?]
at bq_standard.handlers.EventHandler.onEntityLiving(EventHandler.java:133) ~[EventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1986_EventHandler_onEntityLiving_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:575) [ForgeHooks.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095) [vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
> [01:35:41] [Server thread/ERROR] [FML]: Index: 57 Listeners:
> [01:35:41] [Server thread/ERROR] [FML]: 0: HIGHEST
> [01:35:41] [Server thread/ERROR] [FML]: 1: ASM: class WayofTime.bloodmagic.util.handler.event.LivingArmourHandler onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 2: ASM: hellfirepvp.astralsorcery.common.util.effect.time.TimeStopController@4c004453 onLivingTickTest(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 3: NORMAL
> [01:35:41] [Server thread/ERROR] [FML]: 4: ASM: class twilightforest.TFEventListener livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)Z
> [01:35:41] [Server thread/ERROR] [FML]: 5: ASM: class vazkii.botania.common.core.handler.SheddingHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 6: ASM: class WayofTime.bloodmagic.potion.PotionEventHandlers onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 7: ASM: class WayofTime.bloodmagic.util.handler.event.GenericHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 8: ASM: net.darkhax.darkutils.features.shulkerpearl.FeatureShulkerPearlItem@f1c6f7e onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 9: ASM: net.darkhax.darkutils.features.misc.FeatureSheepArmor@3c23952 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 10: ASM: class flaxbeard.immersivepetroleum.common.EventHandler test(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 11: ASM: class nex.handler.LivingHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 12: ASM: class net.insane96mcp.progressivebosses.events.LivingUpdate EventLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 13: ASM: com.shinoow.abyssalcraft.common.handlers.AbyssalCraftEventHooks@249223c2 darkRealm(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 14: ASM: com.shinoow.abyssalcraft.common.handlers.KnowledgeEventHandler@3c4dbd61 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 15: ASM: com.brandon3055.brandonscore.handlers.BCEventHandler@6a1b50ed livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 16: ASM: vazkii.quark.tweaks.feature.BabyZombiesBurn@66c61aa7 entityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 17: ASM: vazkii.quark.tweaks.feature.SheepArmor@79b42b79 onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 18: ASM: vazkii.quark.tweaks.feature.EndermenAntiCheese@753f2cae onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 19: ASM: vazkii.quark.tweaks.feature.DoubleDoors@3ef5d650 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 20: ASM: vazkii.quark.tweaks.feature.LookDownLadders@cd3384f onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 21: ASM: vazkii.quark.tweaks.feature.ChickensShedFeathers@39747de1 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 22: ASM: vazkii.quark.automation.feature.AnimalsEatFloorFood@45210bc4 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 23: ASM: vazkii.quark.world.feature.Biotite@27cd108c onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 24: ASM: vazkii.quark.misc.feature.PoisonPotatoUsage@195147aa onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 25: ASM: vazkii.quark.misc.feature.ParrotEggs@a7c3471 entityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 26: ASM: vazkii.quark.misc.feature.EnderdragonScales@4ffa3c7a onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 27: ASM: morph.avaritia.handler.AbilityHandler@18b391eb updateAbilities(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 28: ASM: jackyy.avaritiatweaks.tweaks.ModEventsHandler@25c517bb armorTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 29: ASM: betterquesting.handlers.EventHandler@164bf5ec onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 30: ASM: lumien.bloodmoon.handler.BloodmoonEventHandler@9d96933 livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 31: ASM: teamroots.embers.itemmod.ModifierCinderJet@733c4c31 onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 32: ASM: teamroots.embers.itemmod.ModifierShiftingScales@51cff1eb onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 33: ASM: teamroots.embers.itemmod.ModifierWindingGears@720a4700 onTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 34: ASM: cpw.mods.ironchest.common.util.OcelotsSitOnChestsHandler@14903182 changeSittingTaskForOcelots(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 35: ASM: p455w0rd.endermanevo.init.ModEvents@26604e1e onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 36: ASM: funwayguy.epicsiegemod.handlers.MainHandler@70e97915 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 37: ASM: funwayguy.epicsiegemod.handlers.entities.PlayerHandler@1bb4fa95 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 38: ASM: class erebus.core.capabilities.base.EntityCapabilityHandler onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 39: ASM: org.cyclops.everlastingabilities.ability.AbilityTypeRegistry@564f9442 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 40: ASM: jackyy.exchangers.handler.EventsHandler@84001ad onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 41: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@724ddd2a entityLivingEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 42: ASM: com.mjr.extraplanets.handlers.MainHandlerServer@69169308 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 43: ASM: com.rwtema.extrautils2.items.ItemLawSword$EventHandlerSword@5e426305 entTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 44: ASM: com.shinoow.grue.common.handlers.GrueEventHandler@5d2e3bb0 spawnGrue(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 45: ASM: net.darkhax.huntingdim.handler.DimensionEffectHandler@673068e3 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 46: ASM: net.darkhax.huntingdim.handler.DimensionEffectHandler@673068e3 onEntityJoinWorld(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 47: ASM: com.buuz135.industrial.proxy.event.MeatFeederTickHandler@4b49966c onTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 48: ASM: com.blakebr0.mysticalagriculture.items.armor.ItemIntermediumArmor$AbilityHandler@47aa5880 updatePlayerAbilityStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 49: ASM: com.blakebr0.mysticalagriculture.items.armor.ItemSuperiumArmor$AbilityHandler@2518ac3d updatePlayerAbilityStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 50: ASM: com.blakebr0.mysticalagriculture.items.armor.ItemSupremiumArmor$AbilityHandler@321087b3 updatePlayerAbilityStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 51: ASM: com.kashdeya.knobcontrol.util.Server@2e6bd2ad playerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 52: ASM: com.kashdeya.knobcontrol.util.Server@2e6bd2ad onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 53: ASM: com.kashdeya.knobcontrol.util.Server@2e6bd2ad entityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 54: ASM: com.kashdeya.knobcontrol.util.Server@2e6bd2ad hungerLoss(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 55: ASM: class mob_grinding_utils.capability.base.EntityCapabilityHandler onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 56: ASM: lumien.randomthings.handler.RTEventHandler@1cbbce2d livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 57: ASM: bq_standard.handlers.EventHandler@3d6c0665 onEntityLiving(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 58: ASM: ts2k16.handlers.EventHandler@17a5ca91 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 59: ASM: Block{minecraft:air} onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 60: ASM: vazkii.botania.common.item.equipment.bauble.ItemTravelBelt@408f8b9 updatePlayerStepStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 61: ASM: vazkii.botania.common.item.equipment.bauble.ItemFlightTiara@f6bd075 updatePlayerFlyStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 62: ASM: xreliquary.items.ItemMobCharm@3d59cb71 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 63: ASM: xreliquary.items.ItemTwilightCloak@7fa3fe11 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 64: ASM: de.ellpeck.actuallyadditions.mod.items.ItemWingsOfTheBats@6a4c6780 livingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 65: ASM: de.ellpeck.actuallyadditions.mod.items.ItemHairyBall@3b76cf59 livingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 66: ASM: soot.potion.PotionWitchBurn@3626cc59 onTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 67: ASM: squeek.appleskin.network.SyncHandler@30fbcb6d onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 68: ASM: class vazkii.botania.common.world.SkyblockWorldEvents onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 69: ASM: li.cil.oc.common.event.NanomachinesHandler$Common$@467eefa2 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 70: ASM: li.cil.oc.common.event.HoverBootsHandler$@43de454c onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 71: ASM: blusunrize.immersiveengineering.common.EventHandler@740496cd onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 72: ASM: tonius.simplyjetpacks.handler.LivingTickHandler@7d2834e5 onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 73: ASM: com.cjm721.overloaded.item.functional.armor.ArmorEventHandler@f88ebfd onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 74: ASM: soot.itemmod.ModifierMundane@606190f5 onTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 75: ASM: tamaized.voidcraft.common.events.VoidicInfusionHandler@368efc9e update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 76: ASM: tamaized.voidcraft.common.events.XiaFlightHandler@2f725e7f updatePlayerFlyStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 77: ASM: mob_grinding_utils.events.ChickenFuseEvent@12c26020 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 78: LOWEST
> [01:35:41] [Server thread/ERROR] [FML]: 79: ASM: class soot.handler.GolemHandler onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/ERROR] [FML]: 80: ASM: ovh.corail.tombstone.handler.EventHandler@455e2b46 onUpdateShadowStep(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
> [01:35:41] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /85.242.23.25:60469
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
at bq_standard.tasks.TaskRetrieval.getPartyProgress(TaskRetrieval.java:461) ~[TaskRetrieval.class:?]
at bq_standard.tasks.TaskRetrieval.detect(TaskRetrieval.java:177) ~[TaskRetrieval.class:?]
at bq_standard.tasks.TaskRetrieval.tickTask(TaskRetrieval.java:85) ~[TaskRetrieval.class:?]
at bq_standard.handlers.EventHandler.onEntityLiving(EventHandler.java:133) ~[EventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1986_EventHandler_onEntityLiving_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:575) ~[ForgeHooks.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
... 9 more
> [01:35:41] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: **Player 1** lost connection: Internal server error
[01:35:41] [Server thread/INFO] [minecraft/DedicatedServer]: **Player 1** left the game
[01:36:43] [Server thread/WARN] [minecraft/EntityTrackerEntry]: Fetching addPacket for removed entity
> [01:36:50] [Server thread/WARN] [minecraft/EntityTrackerEntry]: Fetching addPacket for removed entity```

**Comment by Cazadorsniper** [comment]
Dev is working on the party system in BQ
