### ISSUE TITLE
[Request] Please update EnderIO

### ISSUE THREAD

**Issue by Gumbofizz** [Cazadorsniper/PO3#1629]
Please update EnderIO to latest version as the experience obelisk does not function on current version.
I can do it myself but not sure if it will break anything else?

**Comment by Cazadorsniper** [comment]
Updating Ender IO will cause another issue in the pack, so this can not be done.

**Comment by Gumbofizz** [comment]
Is there a way to fix the error I get when trying to out back experience into the Experience Obelisk? I click the button but nothing happens the sever console just gives the below.

[Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_321]
at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_321]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObelisk.doDrainXP(ContainerExperienceObelisk.java:66) ~[ContainerExperienceObelisk.class:?]
at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObeliskProxy$doDrainXP.lambda$apply$1(ContainerExperienceObeliskProxy$doDrainXP.java:38) ~[ContainerExperienceObeliskProxy$doDrainXP.class:?]
at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:78) ~[ExecPacket$Handler.class:?]
at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:73) ~[ExecPacket$Handler.class:?]
at com.enderio.core.common.network.ThreadedNetworkWrapper$Wrapper$Runner.run(ThreadedNetworkWrapper.java:119) ~[ThreadedNetworkWrapper$Wrapper$Runner.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_321]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_321]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 5 more

**Comment by Cazadorsniper** [comment]
I can only suggest using a different way of storing your XP, I believe Openblocks and MobGrindingUtils have a method of doing so.

**Comment by Gumbofizz** [comment]
Will have a look. Thanks for the help

**Comment by therodet** [comment]
For what it's worth, it's only the XP deposit buttons that are broken. You can Shift + Right-Click on the Obelisk with an Experience Rod to deposit all of your XP. It can then be withdrawn again using the buttons. I keep my XP rod in an item frame next to the obelisk for convenience.
