### ISSUE TITLE
Server keeps crashing dont know what to do exactly

### ISSUE THREAD

**Issue by Trudedsec** [Cazadorsniper/PO3#1641]
here's the crash report of the server I already tried loading a backup of the world that didnt help I looked into the crash report and Was it content Tweaker that caused the crash idk and im not sure on how to go about troubleshooting the issue

[crash-2022-04-05_06.11.44-server.txt](https://github.com/Cazadorsniper/PO3/files/8417266/crash-2022-04-05_06.11.44-server.txt)

**Comment by Trudedsec** [comment]
Pack Version: Mythic

Description: when I go to start the server as normal it goes all the way through until it gets interrupted by something this is what my console tells me 


>net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ContentTweaker (contenttweaker)

Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[Gson.class:?]
        at com.teamacronymcoders.base.savesystem.SaveLoader.getSavedObject(SaveLoader.java:30) ~[SaveLoader.class:?]
        at com.teamacronymcoders.base.materialsystem.MaterialUser.setup(MaterialUser.java:33) ~[MaterialUser.class:?]
        at com.teamacronymcoders.base.BaseModFoundation.preInit(BaseModFoundation.java:96) ~[BaseModFoundation.class:?]
        at com.teamacronymcoders.contenttweaker.ContentTweaker.preInit(ContentTweaker.java:40) ~[ContentTweaker.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[JsonReader.class:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[Gson.class:?]
        at com.teamacronymcoders.base.savesystem.SaveLoader.getSavedObject(SaveLoader.java:30) ~[SaveLoader.class:?]
        at com.teamacronymcoders.base.materialsystem.MaterialUser.setup(MaterialUser.java:33) ~[MaterialUser.class:?]
        at com.teamacronymcoders.base.BaseModFoundation.preInit(BaseModFoundation.java:96) ~[BaseModFoundation.class:?]
        at com.teamacronymcoders.contenttweaker.ContentTweaker.preInit(ContentTweaker.java:40) ~[ContentTweaker.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_321]
[06:11:44] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[06:11:44] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\ender\OneDrive\Desktop\PO3+-+3.4.6server\.\crash-reports\crash-2022-04-05_06.11.44-server.txt
[06:11:44] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[06:11:44] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
Exception in thread "Server thread" [06:11:44] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at appeng.core.AppEng.serverStopped(AppEng.java:271)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at java.lang.reflect.Method.invoke(Unknown Source)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at java.lang.reflect.Method.invoke(Unknown Source)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at java.lang.reflect.Method.invoke(Unknown Source)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:852)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[06:11:44] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:
        at java.lang.Thread.run(Unknown Source)

**Comment by Trudedsec** [comment]
this is what happens when i remove ContentTweaker-1.12.2-4.10.0.jar
[crash-2022-04-05_06.59.51-server.txt](https://github.com/Cazadorsniper/PO3/files/8417417/crash-2022-04-05_06.59.51-server.txt)

**Comment by Cazadorsniper** [comment]
Try replacing the config and script folders with the ones from the client.

**Comment by Trudedsec** [comment]
server is up and running after replacing those files.
