### ISSUE TITLE
Extra planets keeps crashing

### ISSUE THREAD

**Issue by Shadowblue45** [Cazadorsniper/PO3#1709]
**3.4.10**
On start

launcher keeps crashing everytime it gets to extra planets

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -13 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
	at com.mjr.extraplanets.util.GCRecipeUtilities.addSpaceStationRecipe(GCRecipeUtilities.java:20)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.registerSatellitesRecipes(ExtraPlanets_Recipes.java:346)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.initOther(ExtraPlanets_Recipes.java:33)
	at com.mjr.extraplanets.ExtraPlanets.init(ExtraPlanets.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I have tried disabling space stations in Extra planets config but it has not worked for me.

**Comment by wrmthorne** [comment]
I'm also getting this issue. I have tried reinstalling the pack, adding `B:enableMarsSpaceStation=false` to `dimensions.cfg`, setting `B:"Mars SpaceStation"=false` in `ExtraPlanets.cfg`, both at the same time and one at a time and the pack crashes every time. My game was working great until today so I don't know what changed.

**Comment by BlueChaos181** [comment]
bump! I also got this while it was working fine a few hours ago. Good luck guys, awesome pack :]

**Comment by Syvha17** [comment]
Same thing here for my husband and myself. We couldn't load the client because of the :
" Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -13"
So we've changed the "-13" parameter in GALACTICRAFT (planets.cfg) to -1300 (?), there is nothing about that in extraplanets.... 
SO : the client could be lauched... 
BUT it fails to connect to server. 
We both have an error about a "wheat recipe"...
So I think we can"t do much more on our side....
To not be always on bad news, this pack rocks ! it's a very very well done pack ! 
best regards

**Comment by RanonG** [comment]
same here

**Comment by Alienchieff** [comment]
Same here! i played for a good 8 ish hours just fine then all of a sudden the game crashed and kept crashing on startup!! i've done the compatibility stuff and zilch. 
Please please please help!

**Comment by jinga986** [comment]
> So we've changed the "-13" parameter in GALACTICRAFT (planets.cfg) to -1300 (?)

I just did that and while it does fix the crashing on startup, it conflicts with the Custom Recipes and basically locks out all endgame content

**Comment by Syvha17** [comment]
yes I know, that is why i've said we couldn't do more on our client side. We can can do to the login screen with that, but there is more....

**Comment by The-M1k3y** [comment]
I have the same problem and decided to also try fresh installs of 3.4.9 and 3.4.4 which also both have the same crash error. I even tried an old (existing, no new installation) 3.3.61 installation and it also crashes with the same error.

**Comment by D1stribute** [comment]
If you are using CurseForge try using AT Launcher. It fixed it for me

**Comment by RanonG** [comment]
> If you are using CurseForge try using AT Launcher. It fixed it for me

is there any way to transfer world data when you switch launcher?

**Comment by jinga986** [comment]
> is there any way to transfer world data when you switch launcher?

Simple as copying the save file to the new launcher's save file. Using FTB Launcher worked for me since I cannot create an account for the ATL Launcher

**Comment by Alienchieff** [comment]
> If you are using CurseForge try using AT Launcher. It fixed it for me
did the same thing.
Figured out a solution... i was using curseforge. so i swapped to atlauncher and it worked

**Comment by TitusJanshon** [comment]
Im getting the same error no matter what version of PO3 I use also. There seems to be something weird with the minecraft launcher itself; it keeps blinking on and offline

**Comment by 0mori1** [comment]
Config file of extra planets
![Снимок экрана (1447)](https://user-images.githubusercontent.com/117737361/200563878-4eb8a674-e458-4968-b041-59c1a8e2ff73.png)
In-game mod configuration
![Снимок экрана (1446)](https://user-images.githubusercontent.com/117737361/200563916-97dff82f-cc40-438b-8fa2-6ea1e15a0aea.png)

It appears that the game ignores the config file for some reason

**Comment by Syvha17** [comment]
yes, it's the curseforge launcher. ATlauncher worked and we could connect. Thanks for the solution !

**Comment by Cazadorsniper** [comment]
The problem should be clearing up now or some time today, I don't know why extra planets decided to crash when the minecraft launcher/ curse launcher weren't working well.

**Comment by Trompettesib** [comment]
I have the same error since my minecraft launcher update. I think this is why all this stuff is happening but I have no clue about how to fix it. I know that there are already a lot of bugs reported to mojang.

**Comment by twsx** [comment]
Can confirm that the issue has resolved itself with the latest update of Curseforge, at least for me.

From what I gather in the Discords and threads, for anyone still experiencing issues:
* Make sure your Curseforge client has updated successfully:
Click Gear icon in the bottom left, and check, again in the bottom left, that version is **0.212** or newer).
You might need to restart Curse for the update to take place.
* In some cases it can help, or even be necessary, to reset/repair your Minecraft launcher:
Press the 3 dots at the top right, and select "Repair Installation".
**Warning:** This will require you to login to your Mojang/Microsoft account again.
**Addendum:** Some people report having to do this every time they start a pack.

**Comment by Shadowblue45** [comment]
> Can confirm that the issue has resolved itself with the latest update of Curseforge, at least for me.
> 
> From what I gather in the Discords and threads, for anyone still experiencing issues:
> 
> * Make sure your Curseforge client has updated successfully:
>   Click Gear icon in the bottom left, and check, again in the bottom left, that version is **0.212** or newer).
>   You might need to restart Curse for the update to take place.
> * In some cases it can help, or even be necessary, to reset/repair your Minecraft launcher:
>   Press the 3 dots at the top right, and select "Repair Installation".
>   **Warning:** This will require you to login to your Mojang/Microsoft account again.
>   **Addendum:** Some people report having to do this every time they start a pack.

Yup, it ended up working for me after the repair installation. Thanks.
