### ISSUE TITLE
Gardens of glass not working PO3 server

### ISSUE THREAD

**Issue by Banditbutter628** [Cazadorsniper/PO3#1747]
Pack Version: 
Pack Mode : Normal
Multiplayer
Description:
Having trouble getting a Gardens of Glass world to generate i've searched and looked at other reports but they were no help from you previous responses to use the forge jar file to run it or the bat file neither of those actually start the world you run them and they do nothing (the bat file opens cmd but its just because of pause line in the file). And yes i did delete the world folder and tried multiple times
server properties:

#Minecraft server properties
#Tue Apr 25 19:57:18 CDT 2023
allow-flight=false
allow-nether=true
difficulty=1
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=true
generator-settings={"profile"\:"nodamage"}
hardcore=false
level-name=world
level-seed=
level-type=botania-skyblock
max-build-height=256
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=A Minecraft Server
network-compression-threshold=256
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
resource-pack=
resource-pack-sha1=
server-ip=
server-port=25565
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
view-distance=12
white-list=false

**Comment by Cazadorsniper** [comment]
How long are you waiting for the world to start when launching with forge.jar or bat?
PO3 is a big pack its going to take awhile to load.

**Comment by Banditbutter628** [comment]
I will try waiting for longer and see if that works

**Comment by Banditbutter628** [comment]
Well i tried waiting a while and nothing happened like 20 min

**Comment by Banditbutter628** [comment]
when i open them nothing happens no new world file shows up no gui pops up nothing

**Comment by Cazadorsniper** [comment]
There should be a logs folder in the server file post the log on here and i'll take a look.

**Comment by Banditbutter628** [comment]
[19:57:18] [Server thread/INFO]: Starting minecraft server version 1.12.2
[19:57:18] [Server thread/INFO]: Loading properties
[19:57:18] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:293) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:311) ~[?:?]
	at java.io.BufferedInputStream.implRead(BufferedInputStream.java:386) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:365) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:333) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:376) ~[?:?]
	at sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:219) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:173) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:189) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
	at java.io.BufferedReader.implReadLine(BufferedReader.java:371) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:348) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:437) ~[?:?]
	at nz$2.run(SourceFile:100) [minecraft_server.1.12.2.jar:?]
[19:57:18] [Server thread/INFO]: Default game type: SURVIVAL
[19:57:18] [Server thread/INFO]: Generating keypair
[19:57:18] [Server thread/INFO]: Starting Minecraft server on *:25565
[19:57:18] [Server thread/INFO]: Using default channel type
[19:57:18] [Server thread/INFO]: Preparing level "world"
[19:57:18] [Server thread/INFO]: Loaded 488 advancements
[19:57:18] [Server thread/INFO]: Preparing start region for level 0
[19:57:19] [Server thread/INFO]: Preparing spawn area: 13%
[19:57:20] [Server thread/INFO]: Preparing spawn area: 28%
[19:57:21] [Server thread/INFO]: Preparing spawn area: 45%
[19:57:22] [Server thread/INFO]: Preparing spawn area: 67%
[19:57:23] [Server thread/INFO]: Preparing spawn area: 94%
[19:57:24] [Server thread/INFO]: Done (5.788s)! For help, type "help" or "?"
[19:57:48] [User Authenticator #1/INFO]: UUID of player Banditbutter628 is 424246f8-f80e-47b1-927c-1c2513b686de
[19:57:48] [Server thread/INFO]: Banditbutter628[/(deleted ip)] logged in with entity id 2034 at (-211.5, 69.0, 25.5)
[19:57:48] [Server thread/INFO]: Banditbutter628 joined the game
[19:57:53] [Server thread/INFO]: Banditbutter628 lost connection: Disconnected
[19:57:53] [Server thread/INFO]: Banditbutter628 left the game
[19:58:05] [Server thread/INFO]: Stopping the server
[19:58:05] [Server thread/INFO]: Stopping server
[19:58:05] [Server thread/INFO]: Saving players
[19:58:05] [Server thread/INFO]: Saving worlds
[19:58:05] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[19:58:05] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[19:58:05] [Server thread/INFO]: Saving chunks for level 'world'/the_end
[19:58:05] [Server Shutdown Thread/INFO]: Stopping server

**Comment by Banditbutter628** [comment]
when i use the bat or forge jar it doesn't make a new log either

**Comment by Banditbutter628** [comment]
"C:\Program Files\Java\jre1.8.0_301\bin\java.exe" -Xmx10240M -Xms10240M -jar forge-1.12.2-14.23.5.2860.jar 
pause  

and here is the batch file if that helps

**Comment by Cazadorsniper** [comment]
Do you have java 8 version jre1.8.0_301? If not use the one you do have.

**Comment by Banditbutter628** [comment]
yes thats the one im using

**Comment by Cazadorsniper** [comment]
Try updating Java 8 and make sure you get 64bit then change the .bat "301" text with the updated java version.

**Comment by Banditbutter628** [comment]
I just tried it and it still doesn't work

**Comment by Banditbutter628** [comment]
I messed around more and it seems to have fixed part of the string was wrong ill double check the world is correct now

**Comment by Banditbutter628** [comment]
Everything is good. Thanks for your help!
