### ISSUE TITLE
im trying to start a server ( localhost) and every time its makeing a normal world .

### ISSUE THREAD

**Issue by liormalol** [Cazadorsniper/PO3#1783]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa, Mythic):**
**Singleplayer, Multiplayer, or LAN?:**

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by liormalol** [comment]
i tried to delete the world and then change the world type to botania skylock ( level-type=botania-skyblock ) and start the server again and its not working still 
the ( forge-1.12.2-14.23.5.2860 ) dont open at all and when i try the start it didnt work so i change the location to where it is on my computer ( C:\Program Files\Java\jdk-18.0.2.1\bin\java.exe ) and it saying ( C:\Users\benya\OneDrive\שולחן העבודה\po3 server>"C:\Program Files\Java\jdk-17\bin\java.exe" -Xmx6144M -Xms1024M -jar forge-1.12.2-14.23.5.2860.jar nogui"
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

C:\Users\benya\OneDrive\שולחן העבודה\po3 server>pause
Press any key to continue . . . ) 
if you know how to fix it please let my know 
btw i also change the eula to true

**Comment by Cazadorsniper** [comment]
Use Java 8 not 17 or 18.
