### ISSUE TITLE
vanilla world on java 8 and quests not loading

### ISSUE THREAD

**Issue by tommydapleb** [Cazadorsniper/PO3#1786]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.4.11F
**Pack Mode (Normal, Titan, Kappa, Mythic):**Kappa
**Singleplayer, Multiplayer, or LAN?:**Multiplayer

**Description:**
started a sever and whenever i load into the sever it creates a vanilla world. I am on java 8 and even tried importing a single player world to the sever. this fixed the problem. however the quests were not loading
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
[23:39:51] [Server thread/INFO]: Starting minecraft server version 1.12.2
[23:39:51] [Server thread/INFO]: Loading properties
[23:39:51] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_421]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_421]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_421]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_421]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_421]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_421]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_421]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_421]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_421]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_421]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_421]
	at nz$2.run(SourceFile:100) [minecraft_server.1.12.2.jar:?]
[23:39:51] [Server thread/INFO]: Default game type: SURVIVAL
[23:39:51] [Server thread/INFO]: Generating keypair
[23:39:51] [Server thread/INFO]: Starting Minecraft server on 
[23:39:51] [Server thread/INFO]: Using default channel type
[23:39:51] [Server thread/INFO]: Preparing level "world"
[23:39:52] [Server thread/INFO]: Loaded 488 advancements
[23:39:52] [Server thread/INFO]: Preparing start region for level 0
[23:39:53] [Server thread/INFO]: Preparing spawn area: 93%
[23:39:53] [Server thread/INFO]: Done (1.383s)! For help, type "help" or "?"
[23:40:07] [User Authenticator #1/INFO]: UUID of player _TommyDaPleb_ is 
[23:40:07] [Server thread/INFO]: _TommyDaPleb_ logged in with entity id 300 at (2.5, 71.0, 164.5)
[23:40:07] [Server thread/INFO]: _TommyDaPleb_ joined the game

**Comment by Cazadorsniper** [comment]
make sure that the startup file knows where the java 8 path is and you start using forge jar not the minecraft jar.
