### ISSUE TITLE
Crash: Looking at EnderIO machine with building wand equipped

### ISSUE THREAD

**Issue by Nathipha** [Cazadorsniper/PO3#345]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
If I look at a Basic Capacitor Bank (EnderIO) with an Iron Wand (building wand) equipped, my game crashes (the server's fine). I crashed two or three times in a row before I noticed that it was the wand.

**Steps to reproduce:**

- Put an iron wand into slot 1 of your hotbar.
- Put down a single Basic Capacitor Bank (not sure if it has to be powered)
- Scroll to slot 1
- Stand in front of the machine and look at it
- Crash

**Crash log (use pastebin or similar):**
```
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to crazypants.enderio.base.power.forge.item.IInternalPoweredItem
	at crazypants.enderio.base.power.forge.item.InternalPoweredItemCap.<init>(InternalPoweredItemCap.java:15)
	at crazypants.enderio.powertools.machine.capbank.BlockItemCapBank.initCapabilities(BlockItemCapBank.java:22)
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1216)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:98)
	at portablejim.bbw.core.WandWorker.getEquivalentItemStack(WandWorker.java:106)
	at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:91)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:53)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3225_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:680)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1819)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Nathipha** [comment]
I just had another player try it (they used a diamond wand) and they crashed too.

Ad duplicate: I saw the other bug report (#294 ) but "my" crash isn't just happening with any building block, I can look at grass, cobblestone,... and even build using a wand just fine. So far only the capacitor bank is affected and, to be honest, with loading times this long, I'd rather not test every EnderIO machine. Plus, luckily it only crashes my game, not the server.

Ad crash report: Here's the full report: [here](https://pastebin.com/rrE4U3Dw)

Ad mod update: Do you know if the wands or EnderIO causes the crash or is it just compatibility issue? I'll file a bug report with the mod author then too.

**Comment by Cazadorsniper** [comment]
Duplicate meaning I'm aware, I was told on discord about it.
