### ISSUE TITLE
Launcher crashes in the very beginning

### ISSUE THREAD

**Issue by kenieveges** [Cazadorsniper/PO3#600]
3.0.42
Singleplayer

**Can't start the game, launcher crashes**
`[18:18:00] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:18:00] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:18:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:18:00] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2 loading
[18:18:00] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_221, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_221
[18:18:00] [main/INFO] [FML]: Searching C:\Users\kenie\Documents\Curse\Minecraft\Instances\Project Ozone 3 A New Way Forward\mods for mods
[18:18:00] [main/WARN] [FML]: The coremod org.minimallycorrect.libloader.LibLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:18:00] [main/WARN] [FML]: The coremod LibLoader (org.minimallycorrect.libloader.LibLoader) is not signed!
[18:18:01] [ForkJoinPool.commonPool-worker-2/INFO] [LibLoader]: Downloading library org.javassist.javassist-3.22.0-CR1 from https://jcenter.bintray.com/org/javassist/javassist/3.22.0-CR1/javassist-3.22.0-CR1.jar. Expected hash: 1a955bad6b2755153f5abb8ee808b4ac002dc26f8d9c391ebba5d6743d5dd06efc2a1dcb70e5eac0396696f7583ea89f6b5d8c05f971f54f2d56a12a2bb50e82
[18:18:01] [main/INFO] [LibLoader]: Downloading library com.github.javaparser.javaparser-core-3.2.4 from https://jcenter.bintray.com/com/github/javaparser/javaparser-core/3.2.4/javaparser-core-3.2.4.jar. Expected hash: e9ecfe1bd5b9e0532d88093ba565e1420a694b10353243e1c9ba0a32c2aa5a743442df532deb5deeb6d8ab1c3c541e440cc57f1d64b86263e4b1207ed6c12163
[18:18:12] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\kenie\Documents\Curse\Minecraft\Instances\Project Ozone 3 A New Way Forward for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2838.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2838.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2838.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2838.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.net.SocketTimeoutException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.reportException(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_221]
	at org.minimallycorrect.libloader.LibLoaderChained.init(LibLoaderChained.java:68) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
	at org.minimallycorrect.libloader.LibLoader.launch(LibLoader.java:66) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
	at org.minimallycorrect.libloader.LibLoader.init(LibLoader.java:55) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
	at org.minimallycorrect.libloader.LibLoader.<init>(LibLoader.java:25) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) ~[forge-1.12.2-14.23.5.2838.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2838.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2838.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2838.jar:?]
	... 5 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_221]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_221]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_221]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_221]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_221]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_221]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_221]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_221]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_221]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_221]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.access$300(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection$12.run(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection$12.run(Unknown Source) ~[?:1.8.0_221]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_221]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_221]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_221]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_221]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_221]
	at org.minimallycorrect.libloader.LibLoaderChained$Library.openStream(LibLoaderChained.java:208) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
	at org.minimallycorrect.libloader.LibLoaderChained$Library.save(LibLoaderChained.java:258) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
	at org.minimallycorrect.libloader.LibLoaderChained.lambda$init$1(LibLoaderChained.java:68) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_221]
Exception in thread "main" [18:18:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[18:18:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[18:18:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[18:18:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[18:18:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[18:18:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[18:18:12] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
`

**Comment by ByteTemplar** [comment]
You expect people to read that, there is a reason, why there is a "base" message, when you create new issue. So you could add all the necessary information about the problem, making helping easier and possible...
