### ISSUE TITLE
Can't start the pack

### ISSUE THREAD

**Issue by PandaPlay7** [Cazadorsniper/PO3#901]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.5.52
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
Can't start the pack, no loading screen at all, i start the pack it crashes
**Steps to reproduce:**
Start the pack

**Crash log (use pastebin or issue will be closed):**
[00:12:39] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:12:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[00:12:39] [main/INFO]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[00:12:39] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Pedro\Twitch\Minecraft\Install\runtime\jre-x64
[00:12:39] [main/WARN]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[00:12:39] [main/WARN]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[00:12:39] [main/INFO]: Searching C:\Users\Pedro\Twitch\Minecraft\Instances\Project Ozone 3 A New Way Forward\mods for mods
[00:12:39] [main/WARN]: The coremod portablejim.additionalresources.Ar_CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Apotheosis-1.12.2-1.12.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod ApotheosisCore (shadows.ApotheosisCore) is not signed!
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-2.0.0.2.b166.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.10.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/INFO]: [AstralCore] Initialized.
[00:12:39] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[00:12:39] [main/INFO]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CreativeCore_v1.9.90_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: The coremod CreativePatchingLoader (com.creativemd.creativecore.core.CreativePatchingLoader) is not signed!
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.1.30.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.10-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HammerCore-1.12.2-2.0.6.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: The coremod com.creativemd.itemphysic.ItemPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: The coremod ItemPatchingLoader (com.creativemd.itemphysic.ItemPatchingLoader) is not signed!
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-9.8.3.390.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
[00:12:39] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in NotEnoughIDs-1.5.4.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod ru.fewizz.neid.asm.Plugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: The coremod Plugin (ru.fewizz.neid.asm.Plugin) is not signed!
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in OpenComputers-MC1.12.2-1.7.5.192.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod li.cil.oc.common.launch.TransformerLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: The coremod TransformerLoader (li.cil.oc.common.launch.TransformerLoader) is not signed!
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-178.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[00:12:39] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in RandomThings-MC1.12.2-4.2.7.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:39] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in WaitingTime-1.0.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:12:39] [main/WARN]: The coremod com.blamejared.waitingtime.core.WTFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:40] [main/WARN]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:12:40] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50-universal.jar
[00:12:40] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:12:40] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[00:12:40] [main/INFO]: Loading tweak class name codechicken.asm.internal.Tweaker
[00:12:40] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[00:12:40] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Pedro/Twitch/Minecraft/Instances/Project%20Ozone%203%20A%20New%20Way%20Forward/mods/phosphor-1.12.2-0.2.6+build50-universal.jar Service=LaunchWrapper Env=CLIENT
[00:12:40] [main/DEBUG]: Instantiating coremod class PhosphorFMLLoadingPlugin
[00:12:40] [main/DEBUG]: The coremod me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[00:12:40] [main/DEBUG]: Found signing certificates for coremod PhosphorFMLLoadingPlugin (me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin)
[00:12:40] [main/DEBUG]: Found certificate f0387d288626cc2d937daa504e74af570c52a2f1
[00:12:40] [main/DEBUG]: Enqueued coremod PhosphorFMLLoadingPlugin
[00:12:40] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:12:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:12:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:12:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:12:40] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[00:12:40] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[00:12:40] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[00:12:40] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[00:12:40] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[00:12:40] [main/DEBUG]: Injection complete
[00:12:40] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[00:12:40] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[00:12:41] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[00:12:41] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:169) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:114) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:77) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:164) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 2 more
[00:12:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[00:12:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[00:12:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[00:12:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[00:12:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[00:12:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[00:12:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ItsEnder** [comment]
How much ram is allocated?

**Comment by hlevine9** [comment]
This error is a Runtime Exception, meaning that since you crash on launch, this means that you are not allocating enough RAM. You need to allocate at least 6GB (6144MB) RAM. Recommended is 8GB (8192MB).

**Comment by AAHW-Agent** [comment]
Simply put some of the mods lack dependencies like this one:
    [00:12:39] [main/WARN]: Found 
    FMLCorePluginContainsFMLMod marker in 
    OpenComputers-MC1.12.2-1.7.5.192.jar. This is 
    not recommended, @mods should be in a 
    separate jar from the coremod.

Explanation: mods require different libraries/cores/etc (obviously) but when they don't "see" Them, they just put themselves into minecraft (or whatever) and this is why it doesn't pop out like usual or something like that. 
The other "[main/WARN]" Problems Like MCVersion, not signed, are just warning you about potential problems of having different versions/not detecting the licence or proof it's safe. 

Note: this is a THEORETICAL problem explanation, it may worked for me but I CANNOT assure you it will work for you. God my explanation is so bad
